services:
  chain-listener:
    build:
      context: ./memecoindetecting
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "chain_listener.py"]

  tx-parser:
    build:
      context: ./memecoindetecting
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "tx_parser.py"]