services:
  chain-listener:
    build:
      context: ./memecoindetecting
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "chain_listener.py"]

  tx-parser:
    build:
      context: ./memecoindetecting
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "tx_parser.py"]

  posiCOUNT(*) FILTER (WHERE p.status = 'closed' AND p.realized_pnl_sol > 0) AS win ./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    network_COUNT(*) FILTER (WHERE p.status = 'closed' AND p.realized_pnl_sol > 0) AS winommand: ["python3", "position_reducer.py"]

  walCOUNT(*) FILTER (WHERE p.status = 'closed' AND p.realized_pnl_sol > 0) AS win./docker/Dockerfile
    restart: always
    env_file:
      - ./.memecoindetecting.env
    netwoCOUNT(*) FILTER (WHERE p.status = 'closed' AND p.realized_pnl_sol > 0) AS win  command: ["python3", "wallet_reducer.py"]