name: Memecoin Detecting Deploy

on:
  push:
    branches:
      - main
    paths:
      - memecoin_detecting/**
  workflow_dispatch:
    inputs:
      path:
        description: "Path to deploy"
        required: true
        default: "memecoin_detecting/**"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tailscale Login
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ vars.TS_CI_TAG }}

      - name: SCP to Node
        working-directory: memecoin_detecting
        env:
          NODE_IP: ${{ secrets.NODE_IP }}
          NODE_USERNAME: ${{ vars.NODE_USERNAME }}
        run: |
          SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o User=$NODE_USERNAME"
          ssh $SSH_OPTS $NODE_IP "cd /home/rebelforce/scripts/memecoin_trading/ && git pull origin main"
